export default {
	GET_CURRENT_LOCATION:"GET_CURRENT_LOCATION",
	GET_TRANSPORTER_INFORMATION:"GET_TRANSPORTER_INFORMATION",
	GET_TRANSPORTER_LOCATION:"GET_TRANSPORTER_LOCATION",
	GET_DISTANCE_FROM_TRANSPORTER:"GET_DISTANCE_FROM_TRANSPORTER",
    UPDATE_TRANSPORTER_LOCATION:"UPDATE_TRANSPORTER_LOCATION"
};